# Generated by Django 4.2.4 on 2023-08-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_publication']},
        ),
    ]
