# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_pet_photo', models.URLField()),
                ('date_of_birth', models.DateField()),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
